# Generated by Django 5.2.8 on 2026-02-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="login_table",
            name="phone_no",
            field=models.CharField(max_length=15),
        ),
    ]
