# Generated by Django 5.2.8 on 2026-02-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_chatmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="rc_book",
            field=models.FileField(blank=True, default="", null=True, upload_to="pdfs"),
        ),
    ]
